[package]
name = "todo-to-issue"
version = "0.1.0"
authors = ["Sergei Chestakov <sergei332@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
reqwest = "0.9.18"
rpassword = "3.0.2"
serde = "1.0.97"
