[package]
name = "todo-to-issue"
version = "0.1.0"
authors = ["Sergei Chestakov <sergei332@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
console = "0.7.7"
dialoguer = "0.4.0"
glob = "0.3.0"
reqwest = "0.9.18"
serde = "1.0.97"
serde_json = "1.0.40"
